### ISSUE TITLE
Build without HPC registry?

### ISSUE THREAD

**Issue by vsoch** [danbarr/hcp-packer-azure#1]
Hi! I'd like to test this out, but I don't want to have to bring in another service, aside from using Azure. Do you have an example for that? Thanks!

**Comment by danbarr** [comment]
Hi @vsoch, thanks for your interest. I'm not with HashiCorp anymore so I'm really not maintaining these demos going forward. This one was specifically for a session on Azure + HCP Packer, but if you just want to learn how to use Packer to build Azure images, there's a bunch of good blog posts out there.

I had more recent demos in my [hcp-packer-ubuntu22](https://github.com/danbarr/hcp-packer-ubuntu22) repo that use more modern Azure Compute Gallery publishing, but those also use HCP. To use them without HCP, you'd just have to remove the `hcp_packer_registry` block from the build blocks. Then for the "downstream" builds, replace the `hcp-packer-artifact` data sources and instead just reference the parent image directly from the [Compute Gallery following the docs](https://developer.hashicorp.com/packer/integrations/hashicorp/azure/latest/components/builder/arm#shared-image-gallery).
